
title: My Blog
url: 'http://junlulocky.com'
baseurl: '/PanelPedia' #change it according to your repository name



# Profile information
yourname: Ikhwana Luthfi  ## put your name
title: 'DESIGNER'  ## your title
location: Pekanbaru, Riau


## Social Profiles
facebook: http://www.facebook.com/ikhwana luthfi  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com/ikhwana luthfi  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
